package com.example.gamblinggame;

import java.util.concurrent.ThreadLocalRandom;

public class Comparison {
    public static String c;
    static void Compare(int a) {
        int randomNum = ThreadLocalRandom.current().nextInt(100, 1000);
        if(a==randomNum){
            c = "The number generated by the computer is " + randomNum + ". " + "Congrats You Won!";
        } else {
            c = "The number generated by the computer is " + randomNum + ". " + "Better Luck Next Time.";
        }
    }


}
