package com.example.gamblinggame;

import javafx.application.Application;
import javafx.event.ActionEvent;
import javafx.event.EventHandler;
import javafx.geometry.Insets;
import javafx.geometry.Pos;
import javafx.scene.Scene;
import javafx.scene.control.Button;
import javafx.scene.layout.*;
import javafx.scene.paint.Color;
import javafx.scene.text.*;
import javafx.stage.Stage;

import static com.example.gamblinggame.Comparison.Compare;
import static com.example.gamblinggame.Comparison.c;

public class HelloApplication extends Application {
    @Override
    public void start(Stage stage) throws Exception {
        stage.setTitle("Gambling Game");

        // initialisation of the template
        HBox hbox0 = new HBox();
        HBox hbox1 = new HBox(5);
        VBox vbox = new VBox(20);
        HBox hbox2 = new HBox(10);
        HBox hboxSub = new HBox(10);
        HBox hbox3 = new HBox(10);
        StackPane mk = new StackPane();

        // the explanation of the game and some adjustments
        Text intro = new Text("You will enter a 3 digits number (from 100 to 999) and the computer will generate a number at the same range." +
                "\nIf you can guess the number generated by the computer the you win otherwise you can try again. " +
                "\nBEST OF LUCK!");
        intro.setTextAlignment(TextAlignment.CENTER);
        intro.setFont(Font.font("Times New Roman\n", FontWeight.LIGHT, FontPosture.ITALIC, 15));

        // the input area
        Text text = new Text("ENTER 3 DIGITS NUMBER BELOW");
        HBox.setMargin(text, new Insets(10,10,10,10));
        text.setTextAlignment(TextAlignment.CENTER);
        text.setFont(Font.font("Times New Roman\n", FontWeight.BOLD, FontPosture.REGULAR, 17));

        InputBox tf = new InputBox();
        InputBox tf1 = new InputBox();
        InputBox tf2 = new InputBox();


        // the result of the game with mentioning to the number generated by the computer
        Text comment = new Text();
        HBox.setMargin(comment, new Insets(10,10,10,10));
        comment.setTextAlignment(TextAlignment.CENTER);
        comment.setFont(Font.font("Times New Roman\n", FontWeight.LIGHT, FontPosture.ITALIC, 20));

        // the submit button
        Button submitButton = new Button("Submit");
        HBox.setMargin(submitButton, new Insets(10,10,10,10));
        submitButton.setOnAction(new EventHandler<ActionEvent>() {
            @Override
            public void handle(ActionEvent actionEvent) {
                // this class compare between the number given by the computer and the user
                Compare(Integer.parseInt(BindInput(tf, tf1, tf2)));
                comment.setText(c);
            }
        });

        // adjusting the credit section
        Text credit = new Text("Made by MAHDI SAID and KHAIRI HAMMAMi for the java mid-term project" +
                "\nunder the supervision of Mr AHMED BEN HAMOUDA.");
        credit.setTextAlignment(TextAlignment.CENTER);
        credit.setFont(Font.font("Times New Roman\n", FontWeight.LIGHT, FontPosture.REGULAR, 13));

        // adding each section to its parent component
        hbox0.getChildren().addAll(intro);
        hbox0.setAlignment(Pos.CENTER);

        hbox3.getChildren().addAll(text);
        hbox3.setAlignment(Pos.CENTER);

        hbox1.getChildren().addAll(tf.Input(), tf1.Input(), tf2.Input());
        hbox1.setAlignment(Pos.CENTER);

        hboxSub.getChildren().addAll(submitButton);
        hboxSub.setAlignment(Pos.CENTER);

        hbox2.getChildren().addAll(comment);
        hbox2.setAlignment(Pos.CENTER);

        mk.getChildren().addAll(credit);
        mk.setAlignment(Pos.BOTTOM_CENTER);


        vbox.getChildren().addAll(hbox0,hbox3, hbox1, hboxSub, hbox2, mk);

        Scene scene = new Scene(vbox, 850, 380, Color.LIGHTSLATEGREY);
        stage.setScene(scene);
        stage.show();
    }

    private String BindInput(InputBox i1, InputBox i2, InputBox i3) {
        return i1.GetText() + i2.GetText() + i3.GetText();
    }

    public static void main(String[] args) {
        launch();
    }
}